sudo: required
services: 
  -  docker

before_install: 
  - docker build -t mdndocker/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true mdndocker/react-test npm test

after_success: 
  - docker build -t mdndocker/multi-client ./client
  - docker build -t mdndocker/multi-nginx ./nginx
  - docker build -t mdndocker/multi-server ./server
  - docker build -t mdndocker/multi-worker ./worker
  # log in to the docker file
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # take those images and push them to docker hub
  - docker push mdndocker/multi-client 
  - docker push mdndocker/multi-nginx 
  - docker push mdndocker/multi-server 
  - docker push mdndocker/multi-worker 
